### ISSUE TITLE
Project 1 Feedback (Team Garuda)

### ISSUE THREAD

**Issue by pranavacharya** [airavata-courses/Zilean#45]
Hello,

I was really impressed by the architecture of your project.

However, it was not easy to run the project. I would make a suggestion to use docker compose to create all the docker containers in one go. 

Also, using docker and adding command to install all the dependencies would make it easier to run. For Eg. I was prompted to install python3.8-venv 

Attaching screenshot below.
![zilean](https://user-images.githubusercontent.com/22592212/153328766-6e35b922-d09a-468b-be15-4e53e2c69513.png)

Great work. 

Team Garuda (https://github.com/airavata-courses/garuda)

**Comment by impiyush83** [comment]
@pranavacharya  Yep, you require to install Python 3.7+ on your local machine for the setup. It's explicitly mentioned in the readme. 


Thanks for the feedback.


Would recommend to go through the flow by installing this python 3.8

**Comment by pranavacharya** [comment]
Thanks, I followed the step and able to run the project.

Maybe a feature to use docker compose to create multi container env so that no package installation is needed on host machine. This might be easier for user to run the application.
