### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by anbadrin** [airavata-courses/Zilean#46]
Hi,

I was trying to setup your project. I am getting an error zsh: command not found: aws. Could you please give a solution for this?

<img width="526" alt="image" src="https://user-images.githubusercontent.com/97862753/153329201-da683f72-c5b5-48a8-b020-29c965d5d553.png">

**Comment by impiyush83** [comment]
**brew install awscli** will work here.

**Comment by impiyush83** [comment]
Updated the readme 👍🏻  Thanks for the feedback.
