### ISSUE TITLE
Issue By Team Codist

### ISSUE THREAD

**Issue by tanukansalgit** [airavata-courses/Zilean#47]
1. Excellent model
2. Excellent way to achieve communication between microservices(really impressed by Kafka).
3. I personally believe, that instead of connecting many microservices with database, you could have been frugal( which is a good term in software development ).
4.  User/Session service can be integrated together, as to my opinion they are maintaining data about a specific identity and somewhere may serve common purpose.
5. Frontend is very impressive( Hats off to the design ).

**Comment by impiyush83** [comment]
Thanks for the feedback 👍🏻 

Point 3,  each service has its own database. We needed to persist with each entity coming at each microservice. 
Point 4, We thought this like, user-service will serve the purpose of user profile and session-service will service all token-based thing. Hence, once the user is logged in subsequent session checks will only hit session service.  Either way, both approaches are right. System design is always grey.

**Comment by tanukansalgit** [comment]
> Appreciated 👍🏻 
 
I agree with your thoughts, we can develop in either way.  As a suggestion, both the microservices are maintaining same identity-specific data, developing other microservice may not give a profitable output.

But everything looks very impressive, great work!
