### ISSUE TITLE
Project 1 Feedback (by Team Apersand)

### ISSUE THREAD

**Issue by kamblenikhil** [airavata-courses/Zilean#50]
Hi Zilean,

Just 3 things ->
1. I was really impressed by your wiki page.
2. Superb efforts for whole architecture and execution.
3. Detailed and Clean Steps to run the project.

Best,
Nikhil (Team Ampersand)

**Comment by RushikeshPharate** [comment]
Thank you very much for the feedback @kamblenikhil ,
Appreciate it :)
