### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by sumedhsalvi** [airavata-courses/Zilean#51]

**Comment by sumedhsalvi** [comment]
Very well-organized project with clear instructions.  System Architecture, Use case diagram, and Branching pattern diagram is drawn precisely. All the microservices are working with detailed documentation. I am impressed with the implementation of microservice communication through Kafka. However, I did not find Forgot Password option on the login page that can be done as an improvement. Otherwise, Great work by the whole team.
Kudos!

**Comment by RushikeshPharate** [comment]
We will add the forgot password feature in the next sprint.

Thanks for the feedback @sumedhsalvi ,
Appreciate it :)

**Comment by RushikeshPharate** [comment]
Added new issue for the forgot password feature.
#52
